/**
 * Maps MET locationforecast symbol_code values to the legacy numeric IDs used
 * by the nrkno/yr-weather-symbols SVG set. See public/weather/.
 *
 * Source: https://github.com/nrkno/yr-weather-symbols/blob/master/src/index.ts
 */
export const SYMBOL_CODE_TO_ID: Record<string, string> = {
  clearsky_day: "01d",
  clearsky_night: "01n",
  clearsky_polartwilight: "01m",
  fair_day: "02d",
  fair_night: "02n",
  fair_polartwilight: "02m",
  partlycloudy_day: "03d",
  partlycloudy_night: "03n",
  partlycloudy_polartwilight: "03m",
  cloudy: "04",
  rainshowers_day: "05d",
  rainshowers_night: "05n",
  rainshowers_polartwilight: "05m",
  rainshowersandthunder_day: "06d",
  rainshowersandthunder_night: "06n",
  rainshowersandthunder_polartwilight: "06m",
  sleetshowers_day: "07d",
  sleetshowers_night: "07n",
  sleetshowers_polartwilight: "07m",
  snowshowers_day: "08d",
  snowshowers_night: "08n",
  snowshowers_polartwilight: "08m",
  rain: "09",
  heavyrain: "10",
  heavyrainandthunder: "11",
  sleet: "12",
  snow: "13",
  snowandthunder: "14",
  fog: "15",
  sleetshowersandthunder_day: "20d",
  sleetshowersandthunder_night: "20n",
  sleetshowersandthunder_polartwilight: "20m",
  snowshowersandthunder_day: "21d",
  snowshowersandthunder_night: "21n",
  snowshowersandthunder_polartwilight: "21m",
  rainandthunder: "22",
  sleetandthunder: "23",
  lightrainshowersandthunder_day: "24d",
  lightrainshowersandthunder_night: "24n",
  lightrainshowersandthunder_polartwilight: "24m",
  heavyrainshowersandthunder_day: "25d",
  heavyrainshowersandthunder_night: "25n",
  heavyrainshowersandthunder_polartwilight: "25m",
  lightssleetshowersandthunder_day: "26d",
  lightssleetshowersandthunder_night: "26n",
  lightssleetshowersandthunder_polartwilight: "26m",
  heavysleetshowersandthunder_day: "27d",
  heavysleetshowersandthunder_night: "27n",
  heavysleetshowersandthunder_polartwilight: "27m",
  lightssnowshowersandthunder_day: "28d",
  lightssnowshowersandthunder_night: "28n",
  lightssnowshowersandthunder_polartwilight: "28m",
  heavysnowshowersandthunder_day: "29d",
  heavysnowshowersandthunder_night: "29n",
  heavysnowshowersandthunder_polartwilight: "29m",
  lightrainandthunder: "30",
  lightsleetandthunder: "31",
  heavysleetandthunder: "32",
  lightsnowandthunder: "33",
  heavysnowandthunder: "34",
  lightrainshowers_day: "40d",
  lightrainshowers_night: "40n",
  lightrainshowers_polartwilight: "40m",
  heavyrainshowers_day: "41d",
  heavyrainshowers_night: "41n",
  heavyrainshowers_polartwilight: "41m",
  lightsleetshowers_day: "42d",
  lightsleetshowers_night: "42n",
  lightsleetshowers_polartwilight: "42m",
  heavysleetshowers_day: "43d",
  heavysleetshowers_night: "43n",
  heavysleetshowers_polartwilight: "43m",
  lightsnowshowers_day: "44d",
  lightsnowshowers_night: "44n",
  lightsnowshowers_polartwilight: "44m",
  heavysnowshowers_day: "45d",
  heavysnowshowers_night: "45n",
  heavysnowshowers_polartwilight: "45m",
  lightrain: "46",
  lightsleet: "47",
  heavysleet: "48",
  lightsnow: "49",
  heavysnow: "50",
};

export const SYMBOL_LABELS_NB: Record<string, string> = {
  clearsky: "Klarvær",
  fair: "Lettskyet",
  partlycloudy: "Delvis skyet",
  cloudy: "Skyet",
  rainshowers: "Regnbyger",
  rainshowersandthunder: "Regnbyger og torden",
  sleetshowers: "Sluddbyger",
  snowshowers: "Snøbyger",
  rain: "Regn",
  heavyrain: "Kraftig regn",
  heavyrainandthunder: "Kraftig regn og torden",
  sleet: "Sludd",
  snow: "Snø",
  snowandthunder: "Snø og torden",
  fog: "Tåke",
  rainandthunder: "Regn og torden",
  sleetandthunder: "Sludd og torden",
  lightrainshowersandthunder: "Lette regnbyger og torden",
  heavyrainshowersandthunder: "Kraftige regnbyger og torden",
  lightssleetshowersandthunder: "Lette sluddbyger og torden",
  heavysleetshowersandthunder: "Kraftige sluddbyger og torden",
  lightssnowshowersandthunder: "Lette snøbyger og torden",
  heavysnowshowersandthunder: "Kraftige snøbyger og torden",
  lightrainandthunder: "Lett regn og torden",
  lightsleetandthunder: "Lett sludd og torden",
  heavysleetandthunder: "Kraftig sludd og torden",
  lightsnowandthunder: "Lett snø og torden",
  heavysnowandthunder: "Kraftig snø og torden",
  lightrainshowers: "Lette regnbyger",
  heavyrainshowers: "Kraftige regnbyger",
  lightsleetshowers: "Lette sluddbyger",
  heavysleetshowers: "Kraftige sluddbyger",
  lightsnowshowers: "Lette snøbyger",
  heavysnowshowers: "Kraftige snøbyger",
  lightrain: "Lett regn",
  lightsleet: "Lett sludd",
  heavysleet: "Kraftig sludd",
  lightsnow: "Lett snø",
  heavysnow: "Kraftig snø",
};

export function symbolIconPath(symbolCode: string): string | null {
  const id = SYMBOL_CODE_TO_ID[symbolCode];
  return id ? `/weather/${id}.svg` : null;
}

export function symbolLabel(symbolCode: string): string {
  if (!symbolCode) return "";
  const base = symbolCode.split("_")[0];
  return SYMBOL_LABELS_NB[base] ?? base;
}
